name: color_match
description: 颜色匹配游戏
version: 1.0.0

environment:
  sdk: ">=2.19.0 <3.0.0"  
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  vibration: ^3.1.3       
  audioplayers: ^4.0.1    

flutter:
  assets:
    - assets/sounds/
  uses-material-design: true
